(define zero (lambda (f) (lambda (x) x)))
(define (add-1 n)
  (lambda (f) (lambda (x) (f ((n f) x)))))
(define one (lambda (f) (lambda (x) (f x))))
(define two (lambda (f) (lambda (x) (f (f x)))))
(define (+ fm fn)
  (lambda (f) (lambda (x) ((fm f) ((fn f) x)))))

;;----Tests:----
(define (square x)
  (* x x))
((zero square) 2)
((one square) 2)
((two square) 2)
(((+ one two) square) 2)
